# Generated by Django 5.2.17 on 2026-09-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_interactive',
            field=models.BooleanField(default=False),
        ),
    ]
